Module5 task1
htmlacademy-adaptive/465875-pink-21 pull request #12
Opened 2021-01-11 13:02 UTC by kalaganov5

2021-01-11 16:21 UTC, nikkypizza requested changes
Ты об этом уже писал, но проиллюстрирую еще раз для ясности:
**Desktop / Tablet**
![image](https://user-images.githubusercontent.com/30810655/104195905-3fc77180-5434-11eb-8b63-e37787480dc4.png)

**Mobile**
![image](https://user-images.githubusercontent.com/30810655/104196520-eca1ee80-5434-11eb-9bc5-1503492ba826.png)

Больших расхождений между Firefox и Chrome я не заметил. Подгоняй верстку pixPerf в хроме, небольшие различия в других браузерах допустимы. 

[Ты говорил про ошибки иконок](https://s.mail.ru/UY7m/f7tDwgHJq), в [опубликованной версии](https://htmlacademy-adaptive.github.io/465875-pink-21/12/) ругается только на pixel-glass. Значит ошибка локальная на твоей стороне

-----

Стоит привести названия файлов к единому виду. Где-то **logo** является префиксом, где-то постфиксом, у соц сетей нет упоминания, что они логотипы. Где-то **desktop** пишешь полностью, а где-то в одну букву. Есть три версии треугольников.

Советую тебе писать **mobile, tablet, desktop** целиком. Может показаться, что название становится очень длинным, но зато значительно улучшается читаемость. Со временем, когда ты вернешься к этому коду, тебе будет легче в нем разобраться)

-----

В целом хорошая работа, но нужно подчистить код. Сейчас линтер падает потому, что ты пытаешься стилизовать через id, а это против критерия - https://up.htmlacademy.ru/adaptive/21/criteries#d4

2021-01-11 16:21 UTC, nikkypizza commented on source/less/blocks/price.less
> +}
Красоты ради можно добавить плавный переход)
```suggestion
.price__box {
  width: calc(100% * 4 - 160px);
  margin-bottom: 40px;
  transition: transform 0.3s ease-out;
}
```

2021-01-11 16:45 UTC, kalaganov5 commented on source/less/blocks/footer.less
> +      height: 25%;
Очень интересно, круто

2021-01-11 16:51 UTC, kalaganov5 commented on source/less/blocks/price.less
> +  transform: translateX(-25%) translateX(20px);
Большое спасибо за оперативность!

2021-01-12 12:08 UTC, kalaganov5 commented on source/less/blocks/price.less
> +  transform: translateX(-25%) translateX(20px);
расхождений между Firefox и Chrome +

2021-01-12 14:36 UTC, kalaganov5 commented on source/less/blocks/price.less
> +  transform: translateX(-25%) translateX(20px);
названия файлов к единому виду +

2021-01-12 16:00 UTC, kalaganov5 commented on source/less/blocks/table-price.less
> +  }
> Для таких вещей обычно создается отдельный класс типа best-offer
Да, хорошая стратегия

> Тут можно подсократить до одного псевдоэлемента, задать подходящий контент и шрифтовые стили.
+

2021-01-12 16:35 UTC, kalaganov5 commented on source/less/blocks/table-price.less
> +}
Довольно интересно, доработал, код лишний почистил

2021-01-12 20:07 UTC, closed without merging